/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzarendeles;

import javax.swing.JOptionPane;


/**
 *
 * @author foldi
 */
public class Pizza extends javax.swing.JFrame {

    /**
     * Creates new form Pizza
     */
    public Pizza() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        pnlFejlec = new javax.swing.JPanel();
        lblCim = new javax.swing.JLabel();
        lblKep = new javax.swing.JLabel();
        pnlPizza = new javax.swing.JPanel();
        lblPizza = new javax.swing.JLabel();
        rbtSonkas = new javax.swing.JRadioButton();
        rbtMargarita = new javax.swing.JRadioButton();
        rbtHawaii = new javax.swing.JRadioButton();
        rbtSzalami = new javax.swing.JRadioButton();
        pnlMeretek = new javax.swing.JPanel();
        lblMeretek = new javax.swing.JLabel();
        cmbMeretek = new javax.swing.JComboBox<>();
        pnlExtra = new javax.swing.JPanel();
        lblExtra = new javax.swing.JLabel();
        ckbOliva = new javax.swing.JCheckBox();
        ckbKukorica = new javax.swing.JCheckBox();
        ckbGomba = new javax.swing.JCheckBox();
        ckbSajt = new javax.swing.JCheckBox();
        pnlTeszta = new javax.swing.JPanel();
        lblTeszta = new javax.swing.JLabel();
        cmbTeszta = new javax.swing.JComboBox<>();
        pnlLablec = new javax.swing.JPanel();
        btVissza = new javax.swing.JButton();
        btRendel = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PizzaMia");
        setMaximumSize(new java.awt.Dimension(687, 640));
        setMinimumSize(new java.awt.Dimension(490, 390));
        setPreferredSize(new java.awt.Dimension(522, 484));

        pnlFejlec.setBackground(new java.awt.Color(255, 102, 0));
        pnlFejlec.setForeground(new java.awt.Color(255, 102, 0));

        lblCim.setBackground(new java.awt.Color(255, 102, 0));
        lblCim.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        lblCim.setText("ZHome Pizza");

        lblKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\foldi\\Documents\\A_szoftver\\Java\\PizzaRendeles\\pizzajo2.png")); // NOI18N

        javax.swing.GroupLayout pnlFejlecLayout = new javax.swing.GroupLayout(pnlFejlec);
        pnlFejlec.setLayout(pnlFejlecLayout);
        pnlFejlecLayout.setHorizontalGroup(
            pnlFejlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFejlecLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCim, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKep, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFejlecLayout.setVerticalGroup(
            pnlFejlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFejlecLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(lblCim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlPizza.setBackground(new java.awt.Color(255, 204, 153));
        pnlPizza.setForeground(new java.awt.Color(255, 204, 153));

        lblPizza.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        lblPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPizza.setText("Pizza");

        buttonGroup1.add(rbtSonkas);
        rbtSonkas.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        rbtSonkas.setText("Sonkás");

        buttonGroup1.add(rbtMargarita);
        rbtMargarita.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        rbtMargarita.setText("Margarita");
        rbtMargarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMargaritaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtHawaii);
        rbtHawaii.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        rbtHawaii.setText("Hawaii");

        buttonGroup1.add(rbtSzalami);
        rbtSzalami.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        rbtSzalami.setText("Szalámis");

        javax.swing.GroupLayout pnlPizzaLayout = new javax.swing.GroupLayout(pnlPizza);
        pnlPizza.setLayout(pnlPizzaLayout);
        pnlPizzaLayout.setHorizontalGroup(
            pnlPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPizzaLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtSzalami, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtHawaii, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtMargarita, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtSonkas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(pnlPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPizzaLayout.setVerticalGroup(
            pnlPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPizzaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblPizza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtSonkas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtMargarita)
                .addGap(12, 12, 12)
                .addComponent(rbtHawaii)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtSzalami)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMeretek.setBackground(new java.awt.Color(255, 204, 153));

        lblMeretek.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        lblMeretek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMeretek.setText("Méretek : ");

        cmbMeretek.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        cmbMeretek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32 cm", "23 cm", "50 cm", " " }));

        javax.swing.GroupLayout pnlMeretekLayout = new javax.swing.GroupLayout(pnlMeretek);
        pnlMeretek.setLayout(pnlMeretekLayout);
        pnlMeretekLayout.setHorizontalGroup(
            pnlMeretekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeretekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMeretekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMeretek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMeretek, javax.swing.GroupLayout.Alignment.TRAILING, 0, 163, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMeretekLayout.setVerticalGroup(
            pnlMeretekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeretekLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblMeretek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbMeretek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlExtra.setBackground(new java.awt.Color(255, 204, 153));

        lblExtra.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        lblExtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExtra.setText("Extrák");

        ckbOliva.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        ckbOliva.setText("Oliva");
        ckbOliva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbOlivaActionPerformed(evt);
            }
        });

        ckbKukorica.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        ckbKukorica.setText("Kukorica");

        ckbGomba.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        ckbGomba.setText("Gomba");

        ckbSajt.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        ckbSajt.setText("Sajt");

        javax.swing.GroupLayout pnlExtraLayout = new javax.swing.GroupLayout(pnlExtra);
        pnlExtra.setLayout(pnlExtraLayout);
        pnlExtraLayout.setHorizontalGroup(
            pnlExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlExtraLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbSajt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbGomba, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbKukorica, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbOliva, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlExtraLayout.setVerticalGroup(
            pnlExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblExtra)
                .addGap(12, 12, 12)
                .addComponent(ckbOliva)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbKukorica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbGomba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbSajt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTeszta.setBackground(new java.awt.Color(255, 204, 153));

        lblTeszta.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        lblTeszta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeszta.setText("tészta :");

        cmbTeszta.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        cmbTeszta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vastag tészta", "Vékony tészta", "Gluténmentes tészta", " " }));

        javax.swing.GroupLayout pnlTesztaLayout = new javax.swing.GroupLayout(pnlTeszta);
        pnlTeszta.setLayout(pnlTesztaLayout);
        pnlTesztaLayout.setHorizontalGroup(
            pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTesztaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbTeszta, 0, 163, Short.MAX_VALUE)
                    .addComponent(lblTeszta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTesztaLayout.setVerticalGroup(
            pnlTesztaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTesztaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTeszta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlLablec.setBackground(new java.awt.Color(255, 102, 51));
        pnlLablec.setMinimumSize(new java.awt.Dimension(530, 400));

        btVissza.setText("Vissza");

        btRendel.setText("Rendel");
        btRendel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRendelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLablecLayout = new javax.swing.GroupLayout(pnlLablec);
        pnlLablec.setLayout(pnlLablecLayout);
        pnlLablecLayout.setHorizontalGroup(
            pnlLablecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLablecLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVissza, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRendel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlLablecLayout.setVerticalGroup(
            pnlLablecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLablecLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLablecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVissza)
                    .addComponent(btRendel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(pnlExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMeretek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTeszta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
            .addComponent(pnlLablec, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnlFejlec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFejlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlExtra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMeretek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pnlTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(pnlLablec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtMargaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMargaritaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMargaritaActionPerformed

    private void ckbOlivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbOlivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbOlivaActionPerformed

    private void btRendelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRendelActionPerformed
      boolean valasztottPizzaSonka = rbtSonkas.isSelected();
      boolean valasztottPizzaMargarita = rbtMargarita.isSelected();
      boolean valasztottPizzaHawaii = rbtHawaii.isSelected();
      boolean valasztottPizzaSzalami = rbtSzalami.isSelected();
      

      String valasztottPizza = "";
      String valasztottExtra = "";
      String valasztottMeret = "";
      String valasztottTeszta = "";
        
        if (valasztottPizzaHawaii) {
            valasztottPizza = "Választottt pizza: Hawaii\n";
        }
        if (valasztottPizzaMargarita) {
            valasztottPizza = "Választott pizza: Margarita\n";
        }
        if (valasztottPizzaSonka) {
           valasztottPizza = "Választott pizza: Sonkás\n";
        }
        if (valasztottPizzaSzalami) {
            valasztottPizza = "Választott pizza: Szalámis\n";
        }
        else {
             JOptionPane.showMessageDialog(this, "Nincs kiválasztva pizza! Válasszon!", "Hiba", JOptionPane.CANCEL_OPTION);
        }
        
        if (ckbGomba.isSelected()) {
            valasztottExtra = "Választott extra: gomba\n";
        }
        if (ckbKukorica.isSelected()) {
            valasztottExtra = "Választott extra: kukorica\n";
        }
        if (ckbOliva.isSelected()) {
            valasztottExtra = "Választott extra: Oliva\n";
        }
        if (ckbSajt.isSelected()) {
            valasztottExtra = "Választott extra: sajt\n";
        }
        
        valasztottMeret = "Választott méret:" + cmbMeretek.getSelectedItem() + "\n";
        valasztottTeszta = "Választott tészta:" + cmbTeszta.getSelectedItem() + "\n";
        String orderSummary = valasztottPizza + valasztottExtra + valasztottTeszta + valasztottMeret;
        JOptionPane.showMessageDialog(null, orderSummary);
    }//GEN-LAST:event_btRendelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRendel;
    private javax.swing.JButton btVissza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckbGomba;
    private javax.swing.JCheckBox ckbKukorica;
    private javax.swing.JCheckBox ckbOliva;
    private javax.swing.JCheckBox ckbSajt;
    private javax.swing.JComboBox<String> cmbMeretek;
    private javax.swing.JComboBox<String> cmbTeszta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCim;
    private javax.swing.JLabel lblExtra;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblMeretek;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblTeszta;
    private javax.swing.JPanel pnlExtra;
    private javax.swing.JPanel pnlFejlec;
    private javax.swing.JPanel pnlLablec;
    private javax.swing.JPanel pnlMeretek;
    private javax.swing.JPanel pnlPizza;
    private javax.swing.JPanel pnlTeszta;
    private javax.swing.JRadioButton rbtHawaii;
    private javax.swing.JRadioButton rbtMargarita;
    private javax.swing.JRadioButton rbtSonkas;
    private javax.swing.JRadioButton rbtSzalami;
    // End of variables declaration//GEN-END:variables
}
